dataset_path = "../dataset/"
train_data_path = "../dataset/train_data/"
test_data_path = "../dataset/test_data/"
name_path = "../info/names.txt"
stranger_data_path = "../dataset/stranger/"
NAME_CENTER_CSV = "../info/name_center.csv"
SHAPE_PREDICTOR_FILE = "../info/shape_predictor_68_face_landmarks.dat"
STRANGER_SAVE_PATH = "../captured_stranger/"